### ISSUE TITLE
01: Create Design doc and base structure for the Library

### ISSUE THREAD

**Issue by kiranharidas187** [ELEVATE-Project/frontend-authentication-module#1]
## Description
Create an npm library for all the authentication-related flows so that this library can be reused in all the Shikshalokam solution implementations.  This library should include all the implementation and routing of the auth flows. As part of this issue, create a base structure of the application and create an architecture diagram for the implementation.

## Goals
- [ ] Create a base structure for the project and create a library named sl-auth-library
- [ ] Design an architecture doc for the complete implementation. 

## Acceptance Criteria
- [ ] Get the first PR merged with the base structure
- [ ] Update the design dock as part of the readme.md file of the repo

## Implementation Details
Angular, HTML, CSS

## Mockups / Wireframes
All the Auth flows can be viewed in [this](https://mentored.shikshalokam.org/) portal

### Product Name
SL-auth-library

### Project Name
SL-auth-library

### Organization Name:
Shikshalokam

### Domain
Education

### Tech Skills Needed:
Angular, HTML, CSS

### Mentor(s)
Amoghavarsh

### Complexity
Medium

### Category
Features

### Sub Category
Frontend, Library

**Comment by Shruti3004** [comment]
comment

**Comment by huzaifmalik786** [comment]
Greetings, sir @kiranharidas187 , I have gone through all the points that has been mentioned, and under your guidance, I would like to start contributing for the same.

**Comment by priyakumari02** [comment]
@kiranharidas187   , Can I work on this issue , I believe the skills of this project align to my skills. I would like to work on this issue.

**Comment by Sumsum1231** [comment]
@kiranharidas187 **Greetings, I have gone through the goals which to be achieved mentioned above and also I understood the problem statement, Can you please assign this ticket to me?**

**Comment by jaivardhan-bhola** [comment]
Can I work on this @kiranharidas187

**Comment by jaivardhan-bhola** [comment]
Can I work on this @kiranharidas187

**Comment by Ayushmaan06** [comment]
@kiranharidas187 gone through the issues would love to work on it.

**Comment by yashvikram30** [comment]
I have gone through the details of the project and am interested to contribute @kiranharidas187 maam

**Comment by SingAyush** [comment]
I have seen the code base and the tech stack are very familiar to me ,I want to contribute to the project can @kiranharidas187 you assign this #1 issure to me.

**Comment by Y3ABHISHEK** [comment]
@jaivardhan-bhola @yashvikram30 @priyakumari02 @huzaifmalik786 @Sumsum1231 @Ayushmaan06 

https://meet.google.com/xvv-ccjc-duv
You can join the standup at 6:30 PM today to get this ticket!

**Comment by Khushi12Thakur34** [comment]
@Amoghavarsh i would like to raise a pull issue

**Comment by Khushi12Thakur34** [comment]
@kiranharidas187 i would like to work on this

**Comment by psankhe28** [comment]
Hello @kiranharidas187 @Y3ABHISHEK, I'm interested in tackling this issue. Are there any standup meetings scheduled that I can join to get more insights into the project? Additionally, I'd appreciate guidance on how to proceed and if you could provide any references. I have experience in creating a components library using stencil.js and react-storybook. Is the nature of this task similar, or is there something different about it?

**Comment by amoghavarsh** [comment]
Your sending to wrong person I don't know who you

Amoghavarsh Patil

**Comment by Sumsum1231** [comment]
Hello @kiranharidas187  kindly review my PR **https://github.com/ELEVATE-Project/frontend-authentication-module/pull/6**
and guide me if any changes needed.

**Comment by Naval284** [comment]
Hi @kiranharidas187  @Y3ABHISHEK, I  have gone through the goals to be achieved mentioned above and also I understood the problem statement,I am interested in being part of this project, Can you please assign this ticket to me?

**Comment by amoghavarsh** [comment]
No, sorry.

**Comment by Yash-Sajwan24** [comment]
@kiranharidas187 I understand the problem, and I believe I have the necessary skills. Could I have the opportunity to work on this?

**Comment by amoghavarsh** [comment]
No, sorry.

Amogh

**Comment by ayush572** [comment]
Hey @kiranharidas187 ! I have understood the task and looking forward to solve this issue. Can you please assign the same?
