### ISSUE TITLE
02: Login page implementation

### ISSUE THREAD

**Issue by kiranharidas187** [ELEVATE-Project/frontend-authentication-module#2]
## Description
Implement the complete login UI and API flows.  

## Goals
- [ ] Implement the login page UI
- [ ] Complete the API implementation

## Acceptance Criteria
- [ ] Page should flows should work as expected.
- [ ] Page should be made responsive in all screen sizes

## Implementation Details
Angular, HTML, CSS

## Mockups / Wireframes
All the Auth flows can be viewed in [this](https://mentored.shikshalokam.org/) portal

### Product Name
SL-auth-library

### Project Name
SL-auth-library

### Organization Name:
Shikshalokam

### Domain
Education

### Tech Skills Needed:
Angular, HTML, CSS

### Mentor(s)
Amoghavarsh

### Complexity
Medium

### Category
Features

### Sub Category
Frontend, Library

**Comment by Shruti3004** [comment]
test

**Comment by babitarit** [comment]
@kiranharidas187 i would love to work on this issue can u pls assign me this

**Comment by jsam44dev-Harsh** [comment]
This project looks exciting. I would like to work on this project. Can you guide me more on this??

**Comment by Ashurajput02** [comment]
Hey!
I would love to contribute to this.
I am planning to frame the entire UI using angular components and the backend API as well.
Can you please assign this issue to me so I can try working on this.

**Comment by jaivardhan-bhola** [comment]
Hi, Can i work on this? @kiranharidas187

**Comment by ivedmohan** [comment]
Hey, I'm interested in working on this issue.

**Comment by SingAyush** [comment]
I am interested in this can @kiranharidas187 you assign this issue to me.

**Comment by zeel991** [comment]
Hey,i would love to work on this issue , can you please assign it to me ? @kiranharidas187

**Comment by Prayant-M** [comment]
Hey @kiranharidas187, I would like to work on this, could you assign it to me please?

**Comment by SanjayRam07** [comment]
hello @kiranharidas187  , can I work on this issue?
Could you please assign and mentor me?

**Comment by adityarajbisoyi** [comment]
Hello sir, i have worked on the UI of the login page , Below is the screenshot of the implementation since there is no base repository , i would like to know where should i push my code or i can raise a draft PR along with @simran142002 who has worked on the Sign up page.
![image](https://github.com/ELEVATE-Project/frontend-authentication-module/assets/159037169/f3bacba0-a012-48b1-9eac-16a58a1bf6c0)
Link to UI code:
https://github.com/simran142002/SignUpPage/pull/2

**Comment by sagarkori143** [comment]
Hey @kiranharidas187 ! Do we have a design ready so that we can code it or we have to think and build it ourself while coding?

**Comment by ALOK9442** [comment]
hello @kiranharidas187 sir I would like to work on this issue, can you assign it to me? also do we have any design?

**Comment by sagarkori143** [comment]
> Hey @kiranharidas187 ! Do we have a design ready so that we can code it or we have to think and build it ourself while coding?

Friendly reminder. 
@kiranharidas187

**Comment by prakhardotdeb** [comment]
hello @kiranharidas187 sir! I feel i have the skills required for this task and i would love to contribute. Could you please assign this ticket to me?

**Comment by sheffalee** [comment]
@kiranharidas187 sir can u assign me this task as it matches my skill sets and i would like to contribute to this task

**Comment by Yash-Sajwan24** [comment]
@kiranharidas187 I understand the problem, and I believe I have the necessary skills. Could I have the opportunity to work on this?

**Comment by tishubohra** [comment]
@kiranharidas187 I would love to be a part of this project, it would be great if you could assign me this project!

**Comment by Balajisaketh** [comment]
@kiranharidas187 i am confident that i will develop the above task and successfully contribute can you please assign this to me #2

**Comment by HarshitaJaiswal5** [comment]
@kiranharidas187 hello sir! I have studied the problem statement . Could you please assign this task to me ?

**Comment by Guptasameer533** [comment]
Hi @kiranharidas187,

As an experienced **Angular developer,** I possess the requisite skills to implement the **login page UI** and **API flows** effectively. My expertise lies in crafting **responsive designs**, **seamlessly integrating with APIs**, and **conducting comprehensive testing**. I am committed to delivering high-quality work that adheres to the project's standards. 

Furthermore, I am eager to **collaborate** closely with the team to ensure a successful implementation of this feature.

**Comment by Smriti0405** [comment]
Hello, @kiranharidas187 i would love to work on this issue, I am proficient in HTML, CSS and currently learning Angular please assign me this task to me.

**Comment by Akash12233** [comment]
Sir I want work on this project, I have learned HTML, CSS, and learning Angular, you can assign me this project @kiranharidas187

**Comment by Maddy0027** [comment]
@kiranharidas187 there are two issues that you have listed on page one is this one and other is forget password 
 (https://github.com/ELEVATE-Project/frontend-authentication-module/issues/4) I have worked on similar project (https://github.com/Maddy0027/loginApp) which contain both  feature can you tell me where can i create pull request for this

**Comment by Srivastava-Smriti** [comment]
Hello, @kiranharidas187, I have already made a login page using HTML, CSS, JS, and I can make the changes to the layout and the functioning using Angular as per the projects requirements. Can you please assign this ticket to me, here is the image for the reference.
![Screenshot 2024-04-04 115921](https://github.com/ELEVATE-Project/frontend-authentication-module/assets/165574268/0c805611-3f36-4e67-adcb-3425415a7ae0)
