### ISSUE TITLE
04: Forgot password page implementation

### ISSUE THREAD

**Issue by kiranharidas187** [ELEVATE-Project/frontend-authentication-module#4]
## Description
Implement the complete forgot password page UI and API flows.  

## Goals
- [ ] Implement the Forgot password page UI
- [ ] Complete the API implementation

## Acceptance Criteria
- [ ] The forgot password page should work as expected.
- [ ] Page should be made responsive in all screen sizes

## Implementation Details
Angular, HTML, CSS

## Mockups / Wireframes
All the Auth flows can be viewed in [this](https://mentored.shikshalokam.org/) portal

### Product Name
SL-auth-library

### Project Name
SL-auth-library

### Organization Name:
Shikshalokam

### Domain
Education

### Tech Skills Needed:
Angular, HTML, CSS

### Mentor(s)
Amoghavarsh

### Complexity
Medium

### Category
Features

### Sub Category
Frontend, Library

**Comment by Shruti3004** [comment]
test

**Comment by kuv2707** [comment]
I can take up this issue

**Comment by jaivardhan-bhola** [comment]
Hi, Can i work on this? @kiranharidas187

**Comment by arayathegod** [comment]
@kiranharidas187  @Shruti3004 Greetings, I have gone through the goals which to be achieved mentioned above and also I understood the problem statement, Can you please assign this ticket to me?

**Comment by ivedmohan** [comment]
Hey, I'm interested in working on this issue.

**Comment by abansal15** [comment]
Hello @kiranharidas187  could you please assign this issue to me . i am familiar with the tech stack required in this

**Comment by SanjayRam07** [comment]
hello @kiranharidas187  , can I work on this issue?
Could you please assign and mentor me?

**Comment by Sandeep0306** [comment]
Hi @kiranharidas187 i would like to work on this issue. can you assign this to me?

**Comment by kripamehta** [comment]
@kiranharidas187 i am working on this issue, is there any code base available or should we be creating it from scratch?

**Comment by Soham-27** [comment]
hello @kiranharidas187 sir,
I would like to work on this issue. Can you assign this to me?
and is there any code base available ?

**Comment by kripamehta** [comment]
sir @kiranharidas187 i have worked on the ui of this page    with @simran142002 
the link to the code:https://github.com/simran142002/SignUpPage/pull/3/files
![Screenshot 2024-02-12 194221](https://github.com/ELEVATE-Project/frontend-authentication-module/assets/75171844/69957896-c313-49f9-b516-20436be05984)
please give your inputs on the same!

**Comment by prakhardotdeb** [comment]
hello @kiranharidas187  sir! I feels i have skills required for this project and i would love to contributr. Could you please assign this ticket to me?

**Comment by Singh-Supreet** [comment]
@kiranharidas187  I am very confident that I will be able to do this efficiently. I have a lot of experience in making responsive websites. Looking forward to discussing with you

**Comment by Itzsaggy** [comment]
I am interested in this can @kiranharidas187 you assign this issue to me.

**Comment by Yash-Sajwan24** [comment]
@kiranharidas187 I understand the problem, and I believe I have the necessary skills. Could I have the opportunity to work on this?

**Comment by aryangandhi05** [comment]
Hare Krishna @kiranharidas187  Sir I want to solve this issue, as i understand it, and i will give my 100% for solving this issue So please, can you assign me this?

**Comment by Neeharikajha** [comment]
Hello @kiranharidas187 ,
I would like to work on this, can you assign me this?

**Comment by Lahu19** [comment]
Hello there,
 Since I think I can meet the project's requirements and because I have already contributed a PR showcasing my abilities, I would like to offer assistance with the Forgot password page implementation. 

the landing page of https://github.com/Code4GovTech and pull (3) 
I'll be waiting to hear back.

**Comment by Guptasameer533** [comment]
Hi @kiranharidas187,

As an experienced Angular developer, I possess the requisite skills to implement the forgot password page UI and API flows effectively. My expertise lies in crafting responsive designs, seamlessly integrating with APIs, and conducting comprehensive testing. I am committed to deliver high-quality work that adheres to the project's standards.

Furthermore, I am eager to collaborate closely with the team to ensure a successful implementation of this feature.

**Comment by Srivastava-Smriti** [comment]
Hello, @kiranharidas187, I have designed this forgot password page, and I can make the changes to the layout and the functioning using Angular as per the projects requirements. Can you please assign this ticket to me, here is the image for the reference.
![Screenshot 2024-04-04 122120](https://github.com/ELEVATE-Project/frontend-authentication-module/assets/165574268/4baa4da7-f41b-4f67-95d7-b671527c6f65)

**Comment by Srivastava-Smriti** [comment]
Hello, @kiranharidas187, I have designed this forgot password page, and I can make the changes to the layout and the functioning using Angular as per the projects requirements. Can you please assign this ticket to me, here is the image for the reference.
![Screenshot 2024-04-04 123451](https://github.com/ELEVATE-Project/frontend-authentication-module/assets/165574268/20d2889d-ffd8-48f8-b5ee-0e45a74ecec8)

**Comment by SaumyaB24** [comment]
Hello @kiranharidas187, 
I grasp the issue at hand and am confident in my abilities to address it. Would it be possible for me to take on this task?

**Comment by VishnuAmit** [comment]
Hey, @kiranharidas187 I would like to work on this issue. Kindly assign it to me
Thanks.

**Comment by Meet012** [comment]
Hi @kiranharidas187,

I hope you're doing well! I've been eyeing this particular issue and I'm eager to take it on. With my background in HTML, CSS, and Angular, I believe I can make a valuable contribution. Could you please assign this task to me? It would be a fantastic opportunity for me to leverage my skills and help improve this aspect of our project.

Looking forward to your response!

Best regards,
Meet

**Comment by hardik-pratap-singh** [comment]
Hey @kiranharidas187 
I wan to work on this issue under Augtoberfest, C4GT
Kindly assign this issue to me.
